In [50]:
import pickle
import numpy as np
import pandas as pd
from sklearn.externals import joblib
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold, cross_validate

In [51]:
dataset = pd.read_csv('heart.csv')
dataset.head()

age   sex   cp   trestbps   chol   fbs   restecg   thalach  exang  oldpeak  \
0   63     1    3        145    233     1         0       150      0      2.3   
1   37     1    2        130    250     0         1       187      0      3.5   
2   41     0    1        130    204     0         0       172      0      1.4   
3   56     1    1        120    236     0         1       178      0      0.8   
4   57     0    0        120    354     0         1       163      1      0.6   

   slope  ca   thal  target  
0      0   0      1       1  
1      0   0      2       1  
2      2   0      2       1  
3      2   0      2       1  
4      2   0      2       1

In [52]:
label = dataset.iloc[:,-1:].values.ravel()
label

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [53]:
feature = dataset.iloc[:,:-1]
feature.values

array([[63.,  1.,  3., ...,  0.,  0.,  1.],
       [37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       ...,
       [57.,  1.,  0., ...,  1.,  1.,  3.],
       [57.,  0.,  1., ...,  1.,  1.,  2.],
       [56.,  1.,  3., ...,  2.,  2.,  1.]])

In [54]:
X_train, X_test, y_train, y_test = train_test_split(feature, label, test_size=0.3)

In [55]:
print("jumlah data latih : ", len(X_train))
print("jumlah data uji : ", len(X_test))

jumlah data latih :  212
jumlah data uji :  92


In [56]:
knn = KNeighborsClassifier(n_neighbors=9)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=9, p=2,
           weights='uniform')

In [57]:
pred = knn.predict(X_test)
pred

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0], dtype=int64)

In [48]:
cols = {
    'data benar' : y_test,
    'prediksi' : pred,
}
print("hasil")
pd.DataFrame(cols)

hasil


data benar  prediksi
0            1         1
1            0         0
2            1         1
3            1         0
4            1         1
5            1         1
6            1         0
7            1         1
8            0         0
9            0         1
10           0         0
11           0         1
12           1         1
13           1         1
14           1         0
15           0         0
16           1         0
17           0         1
18           0         0
19           1         0
20           0         0
21           1         1
22           0         0
23           0         0
24           1         1
25           1         1
26           1         0
27           0         0
28           0         1
29           1         0
..         ...       ...
62           0         0
63           0         0
64           1         1
65           0         0
66           1         0
67           1         0
68           0         0
69           1         1
70           1         1
71           0         1
72           1         0
73           0         0
74           1         1
75           0         1
76           0         1
77           0         0
78           0         0
79           0         0
80           1         1
81           1         1
82           1         1
83           1         0
84           0         1
85           1         1
86           0         0
87           1         0
88           0         1
89           1         0
90           1         1
91           0         0

[92 rows x 2 columns]

In [49]:
kfold = KFold(n_splits = 10)
scores = ['accuracy', 'precision', 'recall']
results = cross_validate(knn, X_test, y_test, cv=kfold, scoring=scores, return_train_score=True)
results_data = pd.DataFrame(results)
results_data

fit_time  score_time  test_accuracy  train_accuracy  test_precision  \
0  0.002988    0.006992       0.600000        0.670732        0.714286   
1  0.000998    0.015453       0.800000        0.695122        0.714286   
2  0.006990    0.012002       0.555556        0.650602        0.500000   
3  0.001991    0.002992       0.555556        0.759036        0.571429   
4  0.001994    0.011019       0.555556        0.746988        0.571429   
5  0.002050    0.017618       0.555556        0.710843        0.571429   
6  0.001699    0.010348       1.000000        0.662651        1.000000   
7  0.000997    0.011966       0.777778        0.710843        0.800000   
8  0.002055    0.007508       0.444444        0.722892        0.444444   
9  0.001995    0.004752       0.555556        0.698795        0.555556   

   train_precision  test_recall  train_recall  
0         0.649123     0.714286      0.840909  
1         0.666667     1.000000      0.913043  
2         0.650000     0.750000      0.829787  
3         0.724138     0.800000      0.913043  
4         0.704918     0.800000      0.934783  
5         0.683333     0.800000      0.891304  
6         0.639344     1.000000      0.866667  
7         0.671875     0.800000      0.934783  
8         0.693548     1.000000      0.914894  
9         0.677966     1.000000      0.869565

In [31]:
print("Performance Model KNN")

accuracy = results_data.test_accuracy.mean() * 100
precision = results_data.test_precision.mean() * 100
recall = results_data.test_recall.mean() * 100

print("accuracy : %0.2f" % accuracy,"%")
print("precision : %0.2f" % precision, "%")
print("recall : %0.2f" % recall, "%")

Performance Model KNN
accuracy : 72.89 %
precision : 75.29 %
recall : 85.12 %


In [32]:
print(X_test)

     age   sex   cp   trestbps   chol   fbs   restecg   thalach  exang  \
257   50     1    0        144    200     0         0       126      1   
245   48     1    0        124    274     0         0       166      0   
202   58     1    0        150    270     0         0       111      1   
71    51     1    2         94    227     0         1       154      1   
107   45     0    0        138    236     0         0       152      1   
242   64     1    0        145    212     0         0       132      0   
195   59     1    0        170    326     0         0       140      1   
127   67     0    2        152    277     0         1       172      0   
259   38     1    3        120    231     0         1       182      1   
43    53     0    0        130    264     0         0       143      0   
196   46     1    2        150    231     0         1       147      0   
178   43     1    0        120    177     0         0       120      1   
297   59     1    0        164    176 

In [33]:
print(y_test)

[0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0
 1 0 1 0 1 0 0 1 0 1 1 0 0 0 0 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 0 1 1 1 1
 0 1 1 1 0 1 1 1 1 0 1 0 1 1 1 1 0 1]


In [34]:
print(X_train)

     age   sex   cp   trestbps   chol   fbs   restecg   thalach  exang  \
37    54     1    2        150    232     0         0       165      0   
249   69     1    2        140    254     0         0       146      0   
56    48     1    0        122    222     0         0       186      0   
261   52     1    0        112    230     0         1       160      0   
101   59     1    3        178    270     0         0       145      0   
180   55     1    0        132    353     0         1       132      1   
125   34     0    1        118    210     0         1       192      0   
239   35     1    0        126    282     0         0       156      1   
80    41     1    2        112    250     0         1       179      0   
98    43     1    2        130    315     0         1       162      0   
131   49     0    1        134    271     0         1       162      0   
153   66     0    2        146    278     0         0       152      0   
40    51     0    2        140    308 

In [35]:
print(y_train)

[1 0 1 0 1 0 1 0 1 1 1 1 1 0 0 0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 1 0 0 1
 1 0 0 1 0 0 1 0 0 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 1 0 0 1 0
 1 0 0 1 1 0 0 1 1 0 0 0 1 1 1 0 0 1 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 1 1 1
 1 0 0 1 1 1 1 1 0 1 0 1 1 1 0 1 1 0 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0
 0 1 0 0 0 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 1 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0
 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 0 0 0 1 1 0 1 1 0 1]
